set_property PACKAGE_PIN AL12 [get_ports {led_out[7]}]
set_property PACKAGE_PIN AH14 [get_ports {led_out[6]}]
set_property PACKAGE_PIN AH13 [get_ports {led_out[5]}]
set_property PACKAGE_PIN AJ15 [get_ports {led_out[4]}]
set_property PACKAGE_PIN AJ14 [get_ports {led_out[3]}]
set_property PACKAGE_PIN AE13 [get_ports {led_out[2]}]
set_property PACKAGE_PIN AF13 [get_ports {led_out[1]}]
set_property PACKAGE_PIN AG14 [get_ports {led_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_out[0]}]

